units: Imperial
simple:
  template: "{weather_icon} {temperature | round}{temperature_unit} \ue34b {wind_speed | round} - {wind_gusts | round}"
waybar:
  text: "{weather_icon}  {temperature | round}{temperature_unit} \ue34b  {wind_speed | round} - {wind_gusts | round}"
  hot_temperature: 30
  cold_temperature: 0
