# Change the default Omarchy look'n'feel

# https://wiki.hyprland.org/Configuring/Variables/#general
general {
    # No gaps between windows or borders
    gaps_in = 10
    gaps_out = 20
    border_size = 3
    resize_on_border = true
    extend_border_grab_area = 20

    col.active_border = 0xbb8487d2
    col.inactive_border = 0x448487d2

    # Use master layout instead of dwindle
    # layout = master
}

dwindle { 
    # preserve_split = true
}

# https://wiki.hyprland.org/Configuring/Variables/#decoration
decoration {
    # Use round window corners
    rounding = 40
    rounding_power = 1.0
    active_opacity = 1.0
    inactive_opacity = 0.8
    fullscreen_opacity = 1.0
    dim_inactive = true
    dim_strength = 0.1
    # border_part_of_window = false
    blur {
        size = 10
    }
}

# https://wiki.hypr.land/Configuring/Variables/#layout
layout {
    # Avoid overly wide single-window layouts on wide screens
    # single_window_aspect_ratio = 1 1
}
